apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: my-app

manifests:
  helm:
    flags:
      global:
        - --post-renderer=./token.bash
    releases:
      - name: skaffold-templated
        chartPath: charts
        skipBuildDependencies: true
        setValueTemplates:
          token: 'some-token'
